#!/bin/bash
do/jslint
source do/util

sanchezVersion=`getVersion`
echo "# Got version as $sanchezVersion"

targetFile=bin/sanchez.$sanchezVersion.min.js
echo "# Uglifying javascript to $targetFile..."
/usr/bin/env uglifyjs src/sanchez.js > $targetFile
echo "# Uglification complete."

ls -al bin

